@endpoint=http://localhost:{{$dotenv PORT}}


//----testés et fonctionnel--------

### Récupération de l'event avec l'id 1
GET {{endpoint}}/event/1

### Récupération de l'event avec l'id 6
GET {{endpoint}}/event/6

### Récupération du user avec l'id 1
GET {{endpoint}}/user/1

### Récupération du user avec l'id 9
GET {{endpoint}}/user/6

### Récupération de tous les events
GET {{endpoint}}/events


### register un user
POST {{endpoint}}/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password123",
  "password_confirmation": "password123",
  "about": "Hello, I'm John Doe",
  "profil_picture": "https://example.com/profile.jpg"
}


### Connexion et récupération du token
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Utilisation du token pour accéder à la route de son profil protégée
GET {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzIwNDQ5OTA5LCJleHAiOjE3MjA0NTM1MDl9.bzzLghGakLjX93JoOAGld11UjYAj9jvbGnCjECK6n8g



### Utilisation du token pour accéder à la route modif du profil protégée
patch {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzIwNDQ5OTA5LCJleHAiOjE3MjA0NTM1MDl9.bzzLghGakLjX93JoOAGld11UjYAj9jvbGnCjECK6n8g
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password321",
  "password_confirmation": "password321",
  "about": "Hello, I'm John Doe and I'm a developer",
  "profil_picture": "https://example.com/profile.jpg"
}


### delete son profil
DELETE {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzIwNDQ4MzEyLCJleHAiOjE3MjA0NTE5MTJ9.IhjNvrg1J1tuYV8qD_iL3XrrMHk7GmlEwcYMANyRgQo
