@endpoint=http://localhost:{{$dotenv PORT}}


//----user-----------------------------------------------

### register un user
POST {{endpoint}}/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password123",
  "password_confirmation": "password123",
  "about": "Hello, I'm John Doe",
  "profil_picture": "https://example.com/profile.jpg"
}


### Connexion et récupération du token
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "plantiernoe50@gmail.com",
  "password": "password321"
}

### Utilisation du token pour accéder à la route protégée de son profil 
GET {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzIxMDUxNDM0LCJleHAiOjE3MjEwNTUwMzR9.UcTi94G1z2ZZhyaaDK0dguSqlf7jX1wnHhC3XqKR1j8
### Utilisation du token pour accéder à la route update du profil protégé
patch {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjMzMzkzLCJleHAiOjE3MjA2MzY5OTN9.yTuI935hjy_y3Qd-x3-gJEktn9yI60jL0ubLWHAVKHs
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password321",
  "password_confirmation": "password321",
  "about": "Hello, I'm John Doe and I'm a developer",
  "profil_picture": "https://example.com/profile.jpg"
}

### Récupération du user avec l'id 1
GET {{endpoint}}/user/1

### Récupération du user avec l'id 9 (non créé en BDD)
GET {{endpoint}}/user/6


### delete son profil
DELETE {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjg3MzYxLCJleHAiOjE3MjA2OTA5NjF9.wcoPbJHA4oiR_3M07IiP8DuMDv-Pmf3RdBKeR07bzKs


//----event-----------------------------------------------

### Créer un évènement 
post {{endpoint}}/event
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjg3MzYxLCJleHAiOjE3MjA2OTA5NjF9.wcoPbJHA4oiR_3M07IiP8DuMDv-Pmf3RdBKeR07bzKs
Content-Type: application/json

{
  "title": "Soirée pyjama",
  "description": "films et popocorns à volonté.",
  "start_date": "2024-07-17",
  "start_hour": "21:00:00",
  "finish_date": "2024-07-17",
  "address": "9, place des Faubourgs",
  "location": [45.5603292, 4.8064673],
  "privacy_type": false,
  "picture": "https://avatars.githubusercontent.com/u/157673098?v=4",
  "max_attendee": 20,
  "status": false,
  "pmr_access": true,
  "zip_code_city": "69000 Lyon",
  "user_id": 1
  }

### Récupération de l'event avec l'id 1
GET {{endpoint}}/event/1

### Récupération de l'event avec l'id 6 (non créé en BDD)
GET {{endpoint}}/event/6

### getEvent à une distance déterminée avec latitude et longitude
GET {{endpoint}}/events?latitude=48.8549158&longitude=2.3128591&radius=5500000
Content-Type: application/json

### getEvent selon une recherche searchfield et searchtext
GET {{endpoint}}/events?searchfield=title&searchtext=Concert%20Rock
Content-Type: application/json

### Modifier son évènement
patch {{endpoint}}/event/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxMTM0NDI3LCJleHAiOjE3MjExMzgwMjd9.8K0I_q36UhOMJYKYMb6l6p03u3QV3Qkxhll_-M3SQ-c
Content-Type: application/json

{
  "title": "Soirée électro",
  "description": "découvrez le meilleur DJ de Lyon.",
  "start_date": "2024-08-01",
  "start_hour": "21:00:00",
  "finish_date": "2024-08-01",
  "address": "8, rue des Lilas",
  "location": [4.8064673, 45.5603292],
  "privacy_type": false,
  "picture": "https://avatars.githubusercontent.com/u/157673098?v=4",
  "max_attendee": 120,
  "status": false,
  "pmr_access": true,
  "zip_code_city": "69000 Lyon",
  "user_id": 1
}

### delete son event
DELETE {{endpoint}}/event/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjg3MzYxLCJleHAiOjE3MjA2OTA5NjF9.wcoPbJHA4oiR_3M07IiP8DuMDv-Pmf3RdBKeR07bzKs
Content-Type: application/json


//----participation-----------------------------------------------

### l'utilisateur demande à participer à un event
POST  {{endpoint}}/event/1/participate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxMTM0NDI3LCJleHAiOjE3MjExMzgwMjd9.8K0I_q36UhOMJYKYMb6l6p03u3QV3Qkxhll_-M3SQ-c


### l'utilisateur (hôte) accepte une demande de participation
PATCH  {{endpoint}}/event/5/participate/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNzAwNjIzLCJleHAiOjE3MjA3MDQyMjN9.KcL73h5W0RYZUiKEgPAir83_4rhP_0DdN7pfBQerWoo
Content-Type: application/json

{
  "id": 6
}

### annuler sa participation à un évènement 
DELETE  {{endpoint}}/event/1/participate/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzIxMDUxNDM0LCJleHAiOjE3MjEwNTUwMzR9.UcTi94G1z2ZZhyaaDK0dguSqlf7jX1wnHhC3XqKR1j8


### l'utilisateur (hôte) accède aux participants de son event (dont demandes en attente)
GET {{endpoint}}/event/2/participate/all
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjg3MzYxLCJleHAiOjE3MjA2OTA5NjF9.wcoPbJHA4oiR_3M07IiP8DuMDv-Pmf3RdBKeR07bzKs
#Content-Type: application/json

### log Noé
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "plantierlea50@gmail.com",
  "password": "password321"
}

### log Florent
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "florent.desallangre@oclock.school",
  "password": "password321"
}
