@endpoint=http://localhost:{{$dotenv PORT}}


//----testés et fonctionnel--------

### Récupération de l'event avec l'id 1
GET {{endpoint}}/event/1

### Récupération de l'event avec l'id 6
GET {{endpoint}}/event/6

### Récupération du user avec l'id 1
GET {{endpoint}}/user/1

### Récupération du user avec l'id 9
GET {{endpoint}}/user/6

### Récupération de tous les events
GET {{endpoint}}/events

### register un user
POST {{endpoint}}/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password123",
  "password_confirmation": "password123",
  "about": "Hello, I'm John Doe",
  "profil_picture": "https://example.com/profile.jpg"
}


### Connexion et récupération du token
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "plantiernoe50@gmail.com",
  "password": "password321"
}

### Utilisation du token pour accéder à la route de son profil protégée
GET {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjMzMzkzLCJleHAiOjE3MjA2MzY5OTN9.yTuI935hjy_y3Qd-x3-gJEktn9yI60jL0ubLWHAVKHs

### Utilisation du token pour accéder à la route modif du profil protégée
patch {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjMzMzkzLCJleHAiOjE3MjA2MzY5OTN9.yTuI935hjy_y3Qd-x3-gJEktn9yI60jL0ubLWHAVKHs
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "address": "123 Main St",
  "email": "john.doe@example.com",
  "password": "password321",
  "password_confirmation": "password321",
  "about": "Hello, I'm John Doe and I'm a developer",
  "profil_picture": "https://example.com/profile.jpg"
}


### delete son profil
DELETE {{endpoint}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjI5MTE5LCJleHAiOjE3MjA2MzI3MTl9.b4OQ3-8WlsiBXnex7H0ciMSd1k9azsjf7b3GkmpjHYQ

### Test getEvent avec latitude et longitude
GET {{endpoint}}/events?latitude=48.8549158&longitude=2.3128591
Content-Type: application/json


### Test getEvent avec searchfield et searchtext
GET {{endpoint}}/events?searchfield=title&searchtext=Concert%20Rock
Content-Type: application/json


### Modifier son évènement
patch {{endpoint}}/event/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIwNjMzMzkzLCJleHAiOjE3MjA2MzY5OTN9.yTuI935hjy_y3Qd-x3-gJEktn9yI60jL0ubLWHAVKHs
Content-Type: application/json

{
  "title": "Soirée électro",
  "description": "découvrez le meilleur DJ de Lyon.",
  "start_date": "2024-08-01",
  "start_hour": "21:00:00",
  "finish_date": "2024-08-01",
  "address": "8, rue des Lilas",
  "location": [45.5603292, 4.8064673],
  "privacy_type": false,
  "picture": "https://avatars.githubusercontent.com/u/157673098?v=4",
  "max_attendee": 120,
  "status": false,
  "pmr_access": true,
  "zip_code_city": "69000 Lyon",
  "user_id": 1
}